### ISSUE TITLE
Scale font size with media queries by default

### ISSUE THREAD

**Issue by einar-hjortdal** [HimasRafeek/butterCake#7]
Hi, I have been playing around with Butter Cake for the past few days and I like it. I do not know SASS, as I mostly work in LESS, so please answer my following *ignorant* questions regarding the distribution compiled CSS:

- Why did you decide to use px for text-size instead of relatives such as em/rem?
- As they are, font-size does not automatically scale with media queries, will this be addressed?

**Comment by HimasRafeek** [comment]
> Why did you decide to use px for text-size instead of relatives such as em/rem?
I'm used to px, but can be changed to em/rem easily in _variable.scss

> As they are, font-size does not automatically scale with media queries, will this be addressed?
It's not implemented yet, but would be a good Idea for Future Update.

Current Documentation site is coded using Laravel, bit hard to maintain, will be switching soon with new updates and tutorials.

Thank you!
